name: reverence-worship
app_id: da_R36ILtlUZpY1
owner: marc-patrick04
package: .
env:
  APP_NAME: Reverence Worship
  APP_ENV: production
  APP_DEBUG: 'true'
  APP_LOCALE: en
  APP_FALLBACK_LOCALE: en
  APP_FAKER_LOCALE: en_US
  LOG_CHANNEL: stderr
  LOG_LEVEL: debug
  DB_CONNECTION: pgsql
  DB_HOST: ep-lingering-shape-at3vfvkp-pooler.c-9.us-east-1.aws.neon.tech
  DB_PORT: '5432'
  DB_DATABASE: neondb
  DB_USERNAME: neondb_owner
  DB_SSLMODE: require
  SESSION_DRIVER: file
  CACHE_STORE: file
  QUEUE_CONNECTION: sync
  FILESYSTEM_DISK: public
  MAIL_MAILER: log
  BCRYPT_ROUNDS: '12'
capabilities:
  instaboot:
    mode: null
    requests:
    - path: /
debug: true
redirect:
  force_https: true
kind: wasmer.io/App.v0
