export const bibleVersions = [
  { key: "bysb", code: "BYSB", label: "Bibiliya YERA", localFile: "BY.xml" },
  { key: "bir", code: "BIR", label: "Bibiliya Ijambo ry'Imana", localFile: "BIR.xml" },
  { key: "niv", code: "NIV", label: "NIV", localFile: "NIV.xml" },
  { key: "kjv", code: "KJV", label: "KJV", localFile: "KJV.xml" },
  { key: "esv", code: "ESV", label: "ESV", localFile: "ESV.xml" },
];

export const kinyarwandaBibleBookNames: Record<string, string> = {
  GEN: "Itangiriro",
  EXO: "Kuva",
  LEV: "Abalewi",
  NUM: "Kubara",
  DEU: "Gutegeka kwa kabiri",
  JOS: "Yosuwa",
  JDG: "Abacamanza",
  RUT: "Rusi",
  "1SA": "1 Samweli",
  "2SA": "2 Samweli",
  "1KI": "1 Abami",
  "2KI": "2 Abami",
  "1CH": "1 Ibyo ku Ngoma",
  "2CH": "2 Ibyo ku Ngoma",
  EZR: "Ezira",
  NEH: "Nehemiya",
  EST: "Esiteri",
  JOB: "Yobu",
  PSA: "Zaburi",
  PRO: "Imigani",
  ECC: "Umubwiriza",
  SNG: "Indirimbo ya Salomo",
  ISA: "Yesaya",
  JER: "Yeremiya",
  LAM: "Amaganya",
  EZK: "Ezekiyeli",
  DAN: "Daniyeli",
  HOS: "Hoseya",
  JOL: "Yoweli",
  AMO: "Amosi",
  OBA: "Obadiya",
  JON: "Yona",
  MIC: "Mika",
  NAM: "Nahumu",
  HAB: "Habakuki",
  ZEP: "Zefaniya",
  HAG: "Hagayi",
  ZEC: "Zekariya",
  MAL: "Malaki",
  MAT: "Matayo",
  MRK: "Mariko",
  LUK: "Luka",
  JHN: "Yohana",
  ACT: "Ibyakozwe n'Intumwa",
  ROM: "Abaroma",
  "1CO": "1 Abakorinto",
  "2CO": "2 Abakorinto",
  GAL: "Abagalatiya",
  EPH: "Abefeso",
  PHP: "Abafilipi",
  COL: "Abakolosayi",
  "1TH": "1 Abatesalonike",
  "2TH": "2 Abatesalonike",
  "1TI": "1 Timoteyo",
  "2TI": "2 Timoteyo",
  TIT: "Tito",
  PHM: "Filemoni",
  HEB: "Abaheburayo",
  JAS: "Yakobo",
  "1PE": "1 Petero",
  "2PE": "2 Petero",
  "1JN": "1 Yohana",
  "2JN": "2 Yohana",
  "3JN": "3 Yohana",
  JUD: "Yuda",
  REV: "Ibyahishuwe",
};

export const bibleBooks = [
  ["GEN", "Genesis", 50],
  ["EXO", "Exodus", 40],
  ["LEV", "Leviticus", 27],
  ["NUM", "Numbers", 36],
  ["DEU", "Deuteronomy", 34],
  ["JOS", "Joshua", 24],
  ["JDG", "Judges", 21],
  ["RUT", "Ruth", 4],
  ["1SA", "1 Samuel", 31],
  ["2SA", "2 Samuel", 24],
  ["1KI", "1 Kings", 22],
  ["2KI", "2 Kings", 25],
  ["1CH", "1 Chronicles", 29],
  ["2CH", "2 Chronicles", 36],
  ["EZR", "Ezra", 10],
  ["NEH", "Nehemiah", 13],
  ["EST", "Esther", 10],
  ["JOB", "Job", 42],
  ["PSA", "Psalms", 150],
  ["PRO", "Proverbs", 31],
  ["ECC", "Ecclesiastes", 12],
  ["SNG", "Song of Solomon", 8],
  ["ISA", "Isaiah", 66],
  ["JER", "Jeremiah", 52],
  ["LAM", "Lamentations", 5],
  ["EZK", "Ezekiel", 48],
  ["DAN", "Daniel", 12],
  ["HOS", "Hosea", 14],
  ["JOL", "Joel", 3],
  ["AMO", "Amos", 9],
  ["OBA", "Obadiah", 1],
  ["JON", "Jonah", 4],
  ["MIC", "Micah", 7],
  ["NAM", "Nahum", 3],
  ["HAB", "Habakkuk", 3],
  ["ZEP", "Zephaniah", 3],
  ["HAG", "Haggai", 2],
  ["ZEC", "Zechariah", 14],
  ["MAL", "Malachi", 4],
  ["MAT", "Matthew", 28],
  ["MRK", "Mark", 16],
  ["LUK", "Luke", 24],
  ["JHN", "John", 21],
  ["ACT", "Acts", 28],
  ["ROM", "Romans", 16],
  ["1CO", "1 Corinthians", 16],
  ["2CO", "2 Corinthians", 13],
  ["GAL", "Galatians", 6],
  ["EPH", "Ephesians", 6],
  ["PHP", "Philippians", 4],
  ["COL", "Colossians", 4],
  ["1TH", "1 Thessalonians", 5],
  ["2TH", "2 Thessalonians", 3],
  ["1TI", "1 Timothy", 6],
  ["2TI", "2 Timothy", 4],
  ["TIT", "Titus", 3],
  ["PHM", "Philemon", 1],
  ["HEB", "Hebrews", 13],
  ["JAS", "James", 5],
  ["1PE", "1 Peter", 5],
  ["2PE", "2 Peter", 3],
  ["1JN", "1 John", 5],
  ["2JN", "2 John", 1],
  ["3JN", "3 John", 1],
  ["JUD", "Jude", 1],
  ["REV", "Revelation", 22],
].map(([code, name, chapters]) => ({
  code: String(code),
  name: String(name),
  nameRw: kinyarwandaBibleBookNames[String(code)] ?? String(name),
  chapters: Number(chapters),
}));
